export const staticRoutes: Entity.Menu[] = [
  {
    path: '/home',
    title: '概览',
    icon: 'icon-park-outline:analysis',
    pinTab: true,
    menuType: 'page',
    component: '/build-in/home/index.vue',
    id: 1,
    parentId: 0,
  },
  {
    path: '/multi',
    title: '多级菜单演示',
    icon: 'icon-park-outline:list',
    menuType: 'directory',
    id: 2,
    parentId: 0,
  },
  {
    path: '/multi/multi-2',
    title: '多级菜单子页',
    icon: 'icon-park-outline:list',
    menuType: 'page',
    component: '/demo/multi/multi-2/index.vue',
    id: 201,
    parentId: 2,
  },
  {
    path: '/multi/multi-2/detail',
    title: '菜单详情页',
    icon: 'icon-park-outline:list',
    menuVisible: true,
    activePath: '/multi/multi-2',
    menuType: 'page',
    component: '/demo/multi/multi-2/detail/index.vue',
    id: 20101,
    parentId: 2,
  },
  {
    path: '/multi/multi-3',
    title: '多级菜单',
    icon: 'icon-park-outline:list',
    menuType: 'directory',
    id: 202,
    parentId: 2,
  },
  {
    path: '/multi/multi-3/multi-4',
    title: '多级菜单3-1',
    icon: 'icon-park-outline:list',
    component: '/demo/multi/multi-3/multi-4/index.vue',
    id: 20201,
    parentId: 202,
  },
  {
    path: '/list',
    title: '列表页',
    icon: 'icon-park-outline:list-two',
    menuType: 'directory',
    id: 3,
    parentId: 0,
  },
  {
    path: '/list/card-list',
    title: '卡片列表',
    icon: 'icon-park-outline:view-grid-list',
    component: '/demo/list/card-list/index.vue',
    id: 302,
    parentId: 3,
  },
  {
    path: '/list/draggable-list',
    title: '拖拽列表',
    icon: 'icon-park-outline:menu-fold',
    component: '/demo/list/draggable-list/index.vue',
    id: 303,
    parentId: 3,
  },
  {
    path: '/demo',
    title: '功能示例',
    icon: 'icon-park-outline:application-one',
    menuType: 'directory',
    id: 4,
    parentId: 0,
  },
  {
    path: '/demo/fetch',
    title: '请求示例',
    icon: 'icon-park-outline:international',
    component: '/demo/fetch/index.vue',
    id: 401,
    parentId: 4,
  },
  {
    path: '/demo/echarts',
    title: 'ECharts',
    icon: 'icon-park-outline:chart-proportion',
    component: '/demo/echarts/index.vue',
    id: 402,
    parentId: 4,
  },
  {
    path: '/demo/map',
    title: '地图',
    icon: 'carbon:map',
    keepAlive: true,
    component: '/demo/map/index.vue',
    id: 403,
    parentId: 4,
  },
  {
    path: '/demo/editor',
    title: '编辑器',
    icon: 'icon-park-outline:editor',
    menuType: 'directory',
    id: 404,
    parentId: 4,
  },
  {
    path: '/demo/editor/md',
    title: 'MarkDown',
    icon: 'ri:markdown-line',
    component: '/demo/editor/md/index.vue',
    id: 40401,
    parentId: 404,
  },
  {
    path: '/demo/editor/rich',
    title: '富文本',
    icon: 'icon-park-outline:edit-one',
    component: '/demo/editor/rich/index.vue',
    id: 40402,
    parentId: 404,
  },
  {
    path: '/demo/clipboard',
    title: '剪贴板',
    icon: 'icon-park-outline:clipboard',
    component: '/demo/clipboard/index.vue',
    id: 405,
    parentId: 4,
  },
  {
    path: '/demo/icons',
    title: '图标',
    icon: 'local:cool',
    component: '/demo/icons/index.vue',
    id: 406,
    parentId: 4,
  },
  {
    path: '/demo/qr-code',
    title: '二维码',
    icon: 'icon-park-outline:two-dimensional-code',
    component: '/demo/qr-code/index.vue',
    id: 407,
    parentId: 4,
  },
  {
    path: '/demo/cascader',
    title: '省市区联动',
    icon: 'icon-park-outline:add-subset',
    component: '/demo/cascader/index.vue',
    id: 408,
    parentId: 4,
  },
  {
    path: '/demo/dict',
    title: '字典示例',
    icon: 'icon-park-outline:book-one',
    component: '/demo/dict/index.vue',
    id: 409,
    parentId: 4,
  },
  {
    path: '/documents',
    title: '外链文档',
    icon: 'icon-park-outline:file-doc',
    menuType: 'directory',
    id: 5,
    parentId: 0,
  },
  {
    path: '/documents/vue',
    title: 'Vue',
    icon: 'logos:vue',
    component: '/demo/documents/vue/index.vue',
    id: 501,
    parentId: 5,
  },
  {
    path: '/documents/vite',
    title: 'Vite',
    icon: 'logos:vitejs',
    component: '/demo/documents/vite/index.vue',
    id: 502,
    parentId: 5,
  },
  {
    path: 'https://vueuse.org/guide/',
    title: 'VueUse（外链）',
    icon: 'logos:vueuse',
    isLink: true,
    id: 503,
    parentId: 5,
  },

  {
    path: 'https://nova-admin-docs.netlify.app/',
    title: 'Nova docs',
    icon: 'local:logo',
    isLink: true,
    id: 504,
    parentId: 5,
  },
  {
    path: '/public',
    title: '公共示例页（外链）',
    icon: 'local:logo',
    isLink: true,
    id: 505,
    parentId: 5,
  },
  {
    path: '/permission',
    title: '权限',
    icon: 'icon-park-outline:people-safe',
    menuType: 'directory',
    id: 6,
    parentId: 0,
  },
  {
    path: '/permission/permission',
    title: '权限示例',
    icon: 'icon-park-outline:right-user',
    component: '/demo/permission/permission/index.vue',
    id: 601,
    parentId: 6,
  },
  {
    path: '/permission/just-super',
    title: 'super可见',
    icon: 'icon-park-outline:wrong-user',
    component: '/demo/permission/just-super/index.vue',
    id: 602,
    parentId: 6,
  },
  {
    path: '/system',
    title: '系统设置',
    icon: 'icon-park-outline:setting',
    menuType: 'directory',
    id: 7,
    parentId: 0,
  },
  {
    path: '/system/user',
    title: '用户设置',
    icon: 'icon-park-outline:every-user',
    component: '/system/user/index.vue',
    id: 701,
    parentId: 7,
  },
  {
    path: '/system/role',
    title: '角色设置',
    icon: 'icon-park-outline:every-user',
    component: '/system/role/index.vue',
    id: 702,
    parentId: 7,
  },
  {
    path: '/system/dict',
    title: '字典设置',
    icon: 'icon-park-outline:book-one',
    component: '/system/dict/index.vue',
    id: 703,
    parentId: 7,
  },
  {
    path: '/system/menu',
    title: '菜单设置',
    icon: 'icon-park-outline:application-menu',
    component: '/system/menu/index.vue',
    id: 704,
    parentId: 7,
  },
  {
    path: '/system/dept',
    title: '部门管理',
    icon: 'icon-park-outline:application-menu',
    component: '/system/dept/index.vue',
    id: 705,
    parentId: 7,
  },
  {
    path: '/about',
    title: '关于',
    icon: 'icon-park-outline:info',
    component: '/demo/about/index.vue',
    id: 8,
    parentId: 0,
  },
  {
    path: '/user-center',
    title: '个人中心',
    menuVisible: true,
    icon: 'carbon:user-avatar-filled-alt',
    component: '/build-in/user-center/index.vue',
    id: 999,
    parentId: 0,
  },

]
