// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EIcon: typeof import('./../components/custom/EIcon.vue')['default'];
    ErrorTip: typeof import('./../components/common/ErrorTip.vue')['default'];
    NaiveProvider: typeof import('./../components/common/NaiveProvider.vue')['default'];
    Pagination: typeof import('./../components/custom/Pagination.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SvgIcon: typeof import('./../components/custom/SvgIcon.vue')['default'];
  }
}
