// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EIcon: typeof import('./../components/custom/EIcon.vue')['default'];
    ErrorTip: typeof import('./../components/common/ErrorTip.vue')['default'];
    IIconParkOutlineAddOne: typeof import('~icons/icon-park-outline/add-one')['default'];
    IIconParkOutlineAfferent: typeof import('~icons/icon-park-outline/afferent')['default'];
    IIconParkOutlineDownload: typeof import('~icons/icon-park-outline/download')['default'];
    IIconParkOutlineFullScreenTwo: typeof import('~icons/icon-park-outline/full-screen-two')['default'];
    IIconParkOutlineGithub: typeof import('~icons/icon-park-outline/github')['default'];
    IIconParkOutlineMenuFold: typeof import('~icons/icon-park-outline/menu-fold')['default'];
    IIconParkOutlineMenuUnfold: typeof import('~icons/icon-park-outline/menu-unfold')['default'];
    IIconParkOutlineMoon: typeof import('~icons/icon-park-outline/moon')['default'];
    IIconParkOutlineOffScreenTwo: typeof import('~icons/icon-park-outline/off-screen-two')['default'];
    IIconParkOutlineRedo: typeof import('~icons/icon-park-outline/redo')['default'];
    IIconParkOutlineRefresh: typeof import('~icons/icon-park-outline/refresh')['default'];
    IIconParkOutlineRemind: typeof import('~icons/icon-park-outline/remind')['default'];
    IIconParkOutlineSearch: typeof import('~icons/icon-park-outline/search')['default'];
    IIconParkOutlineSettingTwo: typeof import('~icons/icon-park-outline/setting-two')['default'];
    IIconParkOutlineSun: typeof import('~icons/icon-park-outline/sun')['default'];
    IIconParkOutlineToTop: typeof import('~icons/icon-park-outline/to-top')['default'];
    NaiveProvider: typeof import('./../components/common/NaiveProvider.vue')['default'];
    NAvatar: typeof import('naive-ui')['NAvatar'];
    NBackTop: typeof import('naive-ui')['NBackTop'];
    NBadge: typeof import('naive-ui')['NBadge'];
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb'];
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem'];
    NButton: typeof import('naive-ui')['NButton'];
    NCard: typeof import('naive-ui')['NCard'];
    NConfigProvider: typeof import('naive-ui')['NConfigProvider'];
    NDataTable: typeof import('naive-ui')['NDataTable'];
    NDialogProvider: typeof import('naive-ui')['NDialogProvider'];
    NDrawer: typeof import('naive-ui')['NDrawer'];
    NDrawerContent: typeof import('naive-ui')['NDrawerContent'];
    NDropdown: typeof import('naive-ui')['NDropdown'];
    NEllipsis: typeof import('naive-ui')['NEllipsis'];
    NForm: typeof import('naive-ui')['NForm'];
    NFormItemGi: typeof import('naive-ui')['NFormItemGi'];
    NGi: typeof import('naive-ui')['NGi'];
    NGrid: typeof import('naive-ui')['NGrid'];
    NIcon: typeof import('naive-ui')['NIcon'];
    NInput: typeof import('naive-ui')['NInput'];
    NLayout: typeof import('naive-ui')['NLayout'];
    NLayoutContent: typeof import('naive-ui')['NLayoutContent'];
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter'];
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader'];
    NLayoutSider: typeof import('naive-ui')['NLayoutSider'];
    NList: typeof import('naive-ui')['NList'];
    NListItem: typeof import('naive-ui')['NListItem'];
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider'];
    NMenu: typeof import('naive-ui')['NMenu'];
    NMessageProvider: typeof import('naive-ui')['NMessageProvider'];
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider'];
    NPagination: typeof import('naive-ui')['NPagination'];
    NPopover: typeof import('naive-ui')['NPopover'];
    NScrollbar: typeof import('naive-ui')['NScrollbar'];
    NSpace: typeof import('naive-ui')['NSpace'];
    NTab: typeof import('naive-ui')['NTab'];
    NTabPane: typeof import('naive-ui')['NTabPane'];
    NTabs: typeof import('naive-ui')['NTabs'];
    NTag: typeof import('naive-ui')['NTag'];
    NThing: typeof import('naive-ui')['NThing'];
    NTooltip: typeof import('naive-ui')['NTooltip'];
    Pagination: typeof import('./../components/custom/Pagination.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SvgIcon: typeof import('./../components/custom/SvgIcon.vue')['default'];
  }
}
